version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgresql
      - DB_PASSWORD=postgresql
      - DB_NAME=postgresql

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=postgresql
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
